parameters:
  kapitan:
    vars:
      target: ${target_name}
      namespace: ${target_name}
    compile:
      - output_path: ./copy
        input_type: copy
        input_paths:
          - components/adservice/deployment.yaml
          - components/adservice/service.yaml
