apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: front
          image: huntex/frontend:v0.0.2
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/_healthz"
              port: 8080
              httpHeaders:
                - name: "Cookie"
                  value: "shop_session-id=x-readiness-probe"
          env:
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "https://some-catalog-service"
            - name: CURRENCY_SERVICE_ADDR
              value: "https://some-currency-service"
            - name: CART_SERVICE_ADDR
              value: "https://some-cart-service"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "https://some-rec-service"
            - name: CHECKOUT_SERVICE_ADDR
              value: "https://some-checkout-service"
            - name: SHIPPING_SERVICE_ADDR
              value: "https://some-shipping-service"
            - name: AD_SERVICE_ADDR
              value: "https://some-ad-service"
