apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: server
          image: huntex/frontend:1
          env:
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "https://some-catalog-service"
            - name: CURRENCY_SERVICE_ADDR
              value: "https://some-currency-service"
            - name: CART_SERVICE_ADDR
              value: "https://some-cart-service"
            - name: RECOMMENDATION_SERVICE_ADDR
              value: "https://some-rec-service"
            - name: CHECKOUT_SERVICE_ADDR
              value: "https://some-checkout-service"
            - name: SHIPPING_SERVICE_ADDR
              value: "https://some-shipping-service"
            - name: AD_SERVICE_ADDR
              value: "https://some-ad-service"
