apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - image: huntex/frontend:1
    name: frontend
    env:
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "https://some-catalog-service"
    - name: CURRENCY_SERVICE_ADDR
      value: "https://some-currency-service"
    - name: CART_SERVICE_ADDR
      value: "https://some-cart-service"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "https://some-rec-service"
    - name: CHECKOUT_SERVICE_ADDR
      value: "https://some-checkout-service"
    - name: SHIPPING_SERVICE_ADDR
      value: "https://some-shipping-service"
    - name: AD_SERVICE_ADDR
      value: "https://some-ad-service"
  restartPolicy: Never
